name: Release mod

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x ./gradlew
        
      - name: Gradle genIntellijRuns
        run: ./gradlew genIntellijRuns

      - name: Build
        run: ./gradlew build

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar